### ISSUE TITLE
Some node packages 404

### ISSUE THREAD

**Issue by nagisa** [node-red/flow-library#110]
I'm currently playing with the idea of producing a nix flake that contains all nodered packages. To do that I listed all of the packages as known by flows.nodered.org and I found that some, such as

https://flows.nodered.org/node/@moritoko/node-red-contrib-example-lower-case2

are no longer available and 404. Should these disappear from the flow library as well? How long can it take to do so?

**Comment by knolleary** [comment]
Hi @nagisa 

Currently we do not automatically remove modules from the flow library. We used to regularly scan npm for updates, but the npm search was getting too unreliable and inconsistent so it was disabled.

I will run a task to prune the library of modules that are no longer on npm this week.

**Comment by knolleary** [comment]
I have removed 99 nodes that no longer exist on npm.
