### ISSUE TITLE
Displaying Flows

### ISSUE THREAD

**Issue by ImTheDeveloper** [node-red/flow-library#2]
Just an idea:

We have the title, description and then the flow json shown when selecting a flow title from the main page. It would be quite cool to see the flow drawn out (as we have done a few times with screenshots on twitter etc, a picture says 1000 words etc). I find it much easier to see what the flow is about just from seeing it drawn than pasting in the flow to my workspace every time.

Edit: I've just realised there is a list on the right showing what nodes the flow contains but as I say showing it set out would be nice and I assume we have the node positions from the json anyway?

I can imagine when we have a few 100 flows in there it would be far more beneficial to have a quick glance of the flow instead of reading all the description through.

With the above being said, would this make the actual Json pasting redundant as you could mock up a small canvas on the flows page and copy and paste these nodes (as we do now between worksheets) from the flows page to your node red workspace?

**Comment by rajwitt** [comment]
Hi, is there an official way / reusable canvas component now?

**Comment by knolleary** [comment]
No there isn't.

**Comment by rajwitt** [comment]
Thanks for confirming. Started looking for how to do this :)
