### ISSUE TITLE
Org-scoped flows do not correctly check for updates

### ISSUE THREAD

**Issue by sylveon** [node-red/flow-library#40]
I just published a new update to https://www.npmjs.com/package/@pilot-things/node-red-contrib-pilot-things (version 1.4.0) but when I click "check for update" on the [flow library](https://flows.nodered.org/node/@pilot-things/node-red-contrib-pilot-things ), the following error is printed:
```
@pilot-things&#x2F;node-red-contrib-pilot-things: no stable published version
```

**Comment by knolleary** [comment]
Hi @sylveon 

thanks for reporting. This issue is now fixed and live on the flow library.

I've gone ahead and refreshed your module to verify the fix.
